name: Python checker

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings pytest pytest-cov pdoc
        if [ -f requirements.txt ]
        then
          pip install -r requirements.txt
        fi
    - name: Test with pytest
      run: |
        pytest --doctest-modules --cov=. --cov-fail-under=66
    - name: Lint with flake8
      run: |
        flake8 .
    - name: HTML documentation with pdoc
      run: |
        if [ -f __init__.py ]
        then
          pdoc -o docs/ `pwd`
        else
          pdoc -o docs/ `ls --hide=*.md --hide=*.txt --hide=__pycache__`
        fi
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@v1